name: sputnik_test
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  json_serializable: ^6.4.0
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
